### PR TITLE
Use next.js 9.4 env vars

### PR DESCRIPTION
**Pull request by jeanbauer**
https://github.com/strapi/strapi-starter-next-blog/issues/7

### CODE REVIEW

**Comment by Mcastres** [comment]
Is the deployment with Vercel still working with these changes?

**Comment by jshaw** [comment]
Thanks for the Vercel env update. Locally this works great for me. 

I'm trying to use the starter next blog to test the deployment onto Vercel. Everything worked well for deploying the BE to heroku but when deploying to Vercel I'm getting the following errors. This is after I have my NEXT_PUBLIC_API_URL environment variable set to my heroku URL without a trailing slash. ie: NEXT_PUBLIC_API_URL="https://my-url-being-used.herokuapp.com"

I've unsure if this is because there's something incorrect with the graphql URL or if it's the image src coming from the cloudinary image hosting. Any thoughts as to what might be the fix or where I should be looking to see where the problem is?

Below is the when the error shows up in build process "TypeError: Only absolute URLs are supported".

Thanks in advance!

```
22:50:49.604  
[4/4] Building fresh packages...
22:50:49.657  
success Saved lockfile.
22:50:49.660  
Done in 10.08s.
22:50:49.682  
Running "yarn run build"
22:50:49.932  
yarn run v1.22.0
22:50:49.952  
$ next build
22:50:50.495  
Creating an optimized production build...
22:50:50.510  
Attention: Next.js now collects completely anonymous telemetry regarding usage.
22:50:50.510  
This information is used to shape Next.js' roadmap and prioritize features.
22:50:50.510  
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
22:50:50.510  
https://nextjs.org/telemetry
22:50:59.360  
Compiled successfully.
22:50:59.361  
Automatically optimizing pages...
22:50:59.584  
> Build error occurred
22:50:59.586  
TypeError: Only absolute URLs are supported
22:50:59.587  
    at getNodeRequestOptions (/vercel/5d0f3392/frontend/node_modules/next/dist/compiled/node-fetch/index.js:1:145647)
22:50:59.587  
    at /vercel/5d0f3392/frontend/node_modules/next/dist/compiled/node-fetch/index.js:1:147021
22:50:59.587  
    at new Promise (<anonymous>)
22:50:59.587  
    at fetch (/vercel/5d0f3392/frontend/node_modules/next/dist/compiled/node-fetch/index.js:1:146956)
22:50:59.587  
    at fetchAPI (/vercel/5d0f3392/frontend/.next/serverless/pages/category/[id].js:3121:21)
22:50:59.587  
    at getCategories (/vercel/5d0f3392/frontend/.next/serverless/pages/category/[id].js:3180:22)
22:50:59.587  
    at getStaticPaths (/vercel/5d0f3392/frontend/.next/serverless/pages/category/[id].js:897:99)
22:50:59.587  
    at buildStaticPaths (/vercel/5d0f3392/frontend/node_modules/next/dist/build/utils.js:18:86)
22:50:59.587  
    at Object.isPageStatic (/vercel/5d0f3392/frontend/node_modules/next/dist/build/utils.js:25:548)
22:50:59.587  
    at execFunction (/vercel/5d0f3392/frontend/node_modules/jest-worker/build/workers/processChild.js:155:17) {
22:50:59.587  
  type: 'TypeError'
22:50:59.587  
}
22:50:59.621  
error Command failed with exit code 1.
22:50:59.621  
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
22:50:59.633  
Error: Command "yarn run build" exited with 1
22:51:01.549  
Done with "frontend/package.json"
```

**Comment by jeanbauer** [comment]
Sorry, I didnt have time to test the deploy to Vercel yet @Mcastres.

@jshaw you can try to move your .env vars from your .env file to .next.config again under the env block, to see if it works. (I've been running into some issues with vercel and the new .env), also don't forget to remove your .env file for this test.

for example in your next.config.js:

```
...
env: {
    // Will be available on both server and client
    NEXT_PUBLIC_API_URL:
      process.env.NODE_ENV === 'development'
        ? 'http://localhost:3000'
        : 'https://my-url-being-used.herokuapp.com',
}
...
```

**Comment by jshaw** [comment]
Thanks, @jeanbauer, this worked for me first try. Thanks for pointing me in the right direction!

**Pull request merged**
